FROM node:alpine AS builder

WORKDIR /app
ENV PATH /app/node_modules/.bin:$PATH
COPY package.json /app/package.json
RUN npm install --silent
RUN npm install react-scripts@3.0.1 -g
COPY . /app
RUN npm run build

# production environment
FROM nginx:alpine
COPY --from=builder /app/build /usr/share/nginx/html
#COPY --from=builder /app/dist/kitchenFridgeUI/ /usr/share/nginx/html/
COPY --from=builder /app/ssl/ca_bundle.crt /var/certificates/
COPY --from=builder /app/ssl/certificate.crt /var/certificates/
COPY --from=builder /app/ssl/private.key /var/certificates/
COPY --from=builder /app/nginx.conf /etc/nginx/conf.d/default.conf
CMD ["nginx", "-g", "daemon off;"]
